1>------ Build started: Project: Bluprint_splliter_v2, Configuration: Debug ------ 1>C:\Users\Caspian\Source\Repos\Bluprint_splliter\Bluprint_splliter_v2\Program.cs(44,5,44,11): error CS1929: 'string' does not contain a definition for 'Append' and the best extension method overload 'Queryable.Append<string>(IQueryable<string>, string)' requires a receiver of type 'IQueryable<string>' 1>C:\Users\Caspian\Source\Repos\Bluprint_splliter\Bluprint_splliter_v2\Program.cs(50,5,50,9): error CS1929: 'string' does not contain a definition for 'Append' and the best extension method overload 'Queryable.Append<string>(IQueryable<string>, string)' requires a receiver of type 'IQueryable<string>' 1>C:\Users\Caspian\Source\Repos\Bluprint_splliter\Bluprint_splliter_v2\Program.cs(72,9,72,17): error CS0103: The name 'arbetare' does not exist in the current context 1>C:\Users\Caspian\Source\Repos\Bluprint_splliter\Bluprint_splliter_v2\Program.cs(81,31,81,54): error CS0029: Cannot implicitly convert type 'string[]' to 'System.Collections.Generic.List<string>' 1>C:\Users\Caspian\Source\Repos\Bluprint_splliter\Bluprint_splliter_v2\Program.cs(89,14,89,15): error CS0136: A local or parameter named 'i' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter 1>C:\Users\Caspian\Source\Repos\Bluprint_splliter\Bluprint_splliter_v2\Program.cs(20,21,20,39): warning CS8600: Converting null literal or possible null value to non-nullable type. 1>C:\Users\Caspian\Source\Repos\Bluprint_splliter\Bluprint_splliter_v2\Program.cs(23,14,23,24): warning CS8600: Converting null literal or possible null value to non-nullable type. 1>C:\Users\Caspian\Source\Repos\Bluprint_splliter\Bluprint_splliter_v2\Program.cs(26,18,26,36): warning CS8600: Converting null literal or possible null value to non-nullable type. 1>C:\Users\Caspian\Source\Repos\Bluprint_splliter\Bluprint_splliter_v2\Program.cs(68,9,68,15): error CS0165: Use of unassigned local variable 'Mitten' 1>C:\Users\Caspian\Source\Repos\Bluprint_splliter\Bluprint_splliter_v2\Program.cs(89,25,89,30): error CS0165: Use of unassigned local variable 'Block' ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========